name: naxugest_app
description: Application de gestion de stock et démarches administratives ONEE
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Gestion d'état & navigation
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^14.2.1
  postgrest: ^2.5.0


  # Backend Supabase
  supabase_flutter: ^2.9.2
  file_picker: ^8.1.2
  url_launcher: ^6.3.0

  # UI & Design
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0

  # Génération PDF & Excel
  pdf: ^3.10.7
  printing: ^5.12.0
  excel: ^4.0.2

  # Utils
  intl: ^0.19.0
  uuid: ^3.0.7
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  #assets:
    #- assets/images/
    #- assets/icons/
